version: '3.8'

services:
  backend:
    image: kavin2002/backend:latest  # Use the appropriate tag for your backend image
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=mypassword

  frontend:
    image: kavin2002/frontend:latest  # Use the appropriate tag for your frontend image
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: crud
      MYSQL_ROOT_PASSWORD: pass@word1
    ports:
      - "3306:3306"
